hw 1 done
tanya124/smart-home-2021 pull request #1
Opened 2021-03-10 17:34 UTC by tanya124

2021-03-13 16:21 UTC, a-ivanov requested changes

2021-03-13 16:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/manager/DummySmartHomeManager.java
> +        this.lightOnHandler = new LightOnHandler(smartHome, sensorCommandQueue);
DIP: передавайте созданные (в `main`) объекты в конструктор.

2021-03-13 16:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/manager/DummySmartHomeManager.java
> +            case LIGHT_ON:
Нарушение OCP: перепишите так, чтобы можно было добавлять новые обработчики без изменений этого класса.

2021-03-13 16:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/manager/DummySmartHomeManager.java
> +    private LightOnHandler lightOnHandler;
(Hint) Добавьте список `List<EventHandler>`.

2021-03-13 16:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/manager/DummySmartHomeManager.java
> +                    lightOffCommandHandler.doAction(command);
Тоже OCP: передавайте конкретную команду в отправщик команд. Не надо его специализировать на командах по  выключению света.

2021-03-13 16:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/DoorCloseHandler.java
> +                    if (room.getName().equals("hall")) {
SRP: обработка сценария - в отдельном классе.

2021-03-15 07:00 UTC, a-ivanov requested changes

2021-03-15 07:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/reader/JSONObjectStateReader.java
> +    public Object readObjectState(Class clazz){
`<T> T readObject(Class<T> class)... `

2021-03-15 07:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        ArrayList<EventHandler> eventHandlers = new ArrayList<EventHandler>() {{
`List<Handler>... ` объявляйте переменные типом интерфейса.

2021-03-15 07:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/DoorCloseEventHandler.java
> +                        if (room.getName().equals("hall")) {
SRP: обработка сценария - отдельная ответственность, не надо создавать каплинг между обработчиками, они могут легко выполнять свою работу независимо друг от друга.

2021-03-15 11:20 UTC, tanya124 commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        ArrayList<EventHandler> eventHandlers = new ArrayList<EventHandler>() {{
Не очень поняла, что тут имеется ввиду?

2021-03-15 20:58 UTC, tanya124 commented
@a-ivanov cлучайно запушила 2 дз в эту ветку. Это нужно исправить?

2021-03-15 20:59 UTC, tanya124 commented
304730f - последний коммит по первому дз

2021-03-16 05:43 UTC, a-ivanov commented
> @a-ivanov cлучайно запушила 2 дз в эту ветку. Это нужно исправить?

Нормально, посмотрю здесь.

2021-03-22 05:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        ArrayList<EventHandler> eventHandlers = new ArrayList<EventHandler>() {{
`List<Event> events = new ArrayList<>()`, вы работаете с абстракцией List.

2021-03-22 05:53 UTC, a-ivanov requested changes

2021-03-22 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        ArrayList<EventHandler> eventHandlers = new ArrayList<EventHandler>() {{
Лучше не создавать анонимные классы, просто используйте `Arrays.asList`.

2021-03-22 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
> +    public Collection<Room> getRooms() {
Удалите, см. обсуждение в группе.

2021-03-22 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
> +    public SmartHomeSmartIterator createIterator() {
Это лишнее, просто используйте коллекцию внутри execute.

2021-03-22 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
> +    public SmartHomeSmartIterator createIterator() {
Удалите этот метод.

2021-03-24 05:37 UTC, a-ivanov approved these changes

2021-03-24 20:41 UTC, merged